name: Arribada Smart Camera
on:
    push:
        branches:
            - container-deployment
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            actions: write
        steps:
            - name: Set environment variables
              run: |
                REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
                REPO_NAME_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
                echo "REPO_OWNER_LOWER=${REPO_OWNER_LOWER}" >> $GITHUB_ENV
                echo "REPO_NAME_LOWER=${REPO_NAME_LOWER}" >> $GITHUB_ENV
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ env.REPO_NAME_LOWER }}:latest
            - name: Trigger Balena Deploy
              run: |
                curl -X POST "https://api.balena-cloud.com/v6/application(\$(curl -X GET "https://api.balena-cloud.com/v6/application?\$filter=app_name%20eq%20'${{ secrets.BALENA_APP_NAME }}'" -H "Authorization: Bearer ${{ secrets.BALENA_API_KEY }}" -H "Content-Type: application/json" | jq '.d[0].id'))/restart-service" -H "Authorization: Bearer ${{ secrets.BALENA_API_KEY }}" -H "Content-Type: application/json"
              env:
                BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
                BALENA_APP_NAME: ${{ secrets.BALENA_APP_NAME }}
